version: 2
models:
  - name: elections
    description: Elections data
    columns:
      - name: Annee
        description: annee
        tests: [not_null]
        meta:
          dimension:
            type: date
          metrics:
            years_for_election:
              type: date
      - name: Tour
        description: tour
        tests: [not_null]
      - name: Departement
        description: departement
        tests: [not_null]
      - name: Inscrits
        description: inscrits
        tests: [not_null]
        meta:
          metrics:
            number_of_inscrits:
              type: count
      - name: Votants
        description: votants
        tests: [not_null]
        meta:
          metrics:
            number_of_votants:
              type: count
      - name: Abstentions
        description: abstentions
        tests: [not_null]
        meta:
          metrics:
            number_of_abstention:
              type: count
      - name: Nom
        description: nom
        tests: [not_null]
      - name: Voix
        description: voix
        tests: [not_null]
        meta:
          metrics:
            number_of_voix:
             type: count
  - name: resultats_elections
    description: Elections results
    columns:
      - name: Annee
        description: annee
        tests: [not_null]
        meta:
          dimension:
            type: date
          metrics:
            years_of_electionresult:
              type: date
      - name: Nom
        description: nom
        tests: [not_null]
      - name: Taux
        description: taux
        tests: [not_null]
        meta:
          metrics:
            taux_en_count:
               type: count
  - name: securite
    description: "Description du modèle DBT pour les données de géographie."
    columns:
      - name: classe
        description: "Type de classement."
        tests:
          - not_null
      - name: annee
        description: "Année de référence des données."
        tests:
          - not_null
      - name: Code_region
        description: "Code numérique identifiant la région."
        tests:
          - not_null
      - name: unite_de_compte
        description: "Unité de mesure utilisée dans les données."
        tests:
          - not_null
      - name: millPOP
        description: "Population en millions."
        tests:
          - not_null
      - name: millLOG
        description: "Nombre de logements en millions."
        tests:
          - not_null
      - name: faits
        description: "Nombre total de faits enregistrés."
        tests:
          - not_null
        meta:
          metrics:
            number_of_faits:
              type: count
      - name: POP
        description: "Population totale."
        tests:
          - not_null
        meta:
          metrics:
            number_of_populations:
              type: count
      - name: LOG
        description: "Détails des logements, possible problème de formatage."
        tests:
          - not_null
      - name: tauxpourmille
        description: "Taux pour mille, avec formatage de virgule pour les décimales."
        tests:
          - not_null
        meta:
          metrics:
            number_of_tauxpourmille:
              type: count

  - name: emplois
    description: "Tableau des données d'emploi et de salaire par zone d'emploi et région."
    columns:
      - name: zone_d_emploi
        description: "Nom de la zone d'emploi."
        tests:
          - not_null
      - name: region
        description: "Nom de la région."
        tests:
          - not_null
      - name: zone_d_emploi_regionalisee
        description: "Zone d'emploi régionalisée."
        tests:
          - not_null
      - name: annee
        description: "Année de l'enregistrement."
        tests:
          - not_null
        meta:
          dimension:
            type: date
          metrics:
            years_of_enregistrement:
              type: date
      - name: trimestre
        description: "Trimestre de l'enregistrement."
        tests:
          - not_null
      - name: dernier_jour_du_trimestre
        description: "Date du dernier jour du trimestre."
        tests:
          - not_null
        meta:
          dimension:
            type: date
          metrics:
            date_of_dernierjouredutrimestre:
              type: date
      - name: code_region
        description: "Code numérique de la région."
        tests:
          - not_null
      - name: code_zone_d_emploi
        description: "Code numérique de la zone d'emploi."
        tests:
          - not_null
      - name: effectifs_salaries_brut
        description: "Nombre d'effectifs salariés brut."
        tests:
          - not_null
        meta:
          metrics:
            effectifs_salaries_brut_count:
              type: count
      - name: masse_salariale_brut
        description: "Montant de la masse salariale brute."
        tests:
          - not_null
        meta:
          metrics:
            masse_salariale_brut_count:
              type: count
